<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE cards [
  <!ELEMENT cards ANY>
  <!ELEMENT card ANY>
  <!ELEMENT id ANY>
  <!ELEMENT name ANY>
  <!ELEMENT image ANY>
  <!ELEMENT life ANY>
  <!ELEMENT attack ANY>
  <!ELEMENT armor ANY>
  <!ELEMENT heal ANY>
  <!ELEMENT innate ANY>
  <!ELEMENT call ANY>
  <!ELEMENT weakness ANY>
  <!ELEMENT frail ANY>
  <!ELEMENT curse ANY>
  <!ELEMENT blind ANY>
  <!ELEMENT block ANY>
  <!ELEMENT silence ANY>
  <!ELEMENT wound ANY>
  <!ELEMENT world ANY>
  <!ELEMENT sequences ANY>
  ]>
<cards>
    <card><id>0</id><name>Mimic</name><image>e_mimic</image><life>100</life><attack>10</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>mimic</innate><world>treasure</world><sequences>a|p|a|a|a|p|p|p|p|p</sequences></card>

    <!--FOREST-->
    <card><id>1</id><name>Forest Sprite</name><image>e_forest_1</image><life>16</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>a|p|p|a|a|p|a|p|a|da</sequences></card>
    <card><id>2</id><name>Forest Sprite</name><image>e_forest_1</image><life>16</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>p|a|p|a|p|a|a|da|p|p</sequences></card>
    <card><id>3</id><name>Caterpillar</name><image>e_forest_3</image><life>24</life><attack>4</attack><armor>4</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>a|s|a|s|p|da|s|a|s|p</sequences></card>
    <card><id>4</id><name>Butterfly Cocoon</name><image>e_forest_2</image><life>12</life><attack>2</attack><armor>4</armor><heal></heal><call></call><weakness>1</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>cocoon</innate><world>forest</world><sequences>s|s|wa|p|p|s|wa|s|wa|a</sequences></card>
    <card><id>5</id><name>Butterfly Cocoon</name><image>e_forest_2</image><life>12</life><attack>2</attack><armor>4</armor><heal></heal><call></call><weakness>0</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>cocoon</innate><world>forest</world><sequences>s|s|ws|p|p|ws|s|ws|s|a</sequences></card>
    <card><id>6</id><name>Giant Butterfly</name><image>e_forest_4</image><life>48</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>p|a|p|a|p|da|p|da|p|da</sequences></card>
    <card><id>7</id><name>Paralyzing Spider</name><image>e_forest_5</image><life>31</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>1</block><silence>0</silence><wound>0</wound><innate>spider_web</innate><world>forest</world><sequences>a|p|p|wa|a|p|p|wa|a|p</sequences></card>
    <card><id>8</id><name>Paralyzing Spider</name><image>e_forest_5</image><life>31</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>1</block><silence>0</silence><wound>0</wound><innate>spider_web</innate><world>forest</world><sequences>p|p|wa|a|p|p|wa|a|p|p</sequences></card>
    <card><id>9</id><name>Horned Frog</name><image>e_forest_6</image><life>35</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>frog_melody</innate><world>forest</world><sequences>a|p|a|a|p|da|p|da|da|p</sequences></card>
    <card><id>10</id><name>Horned Frog</name><image>e_forest_6</image><life>35</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>frog_melody</innate><world>forest</world><sequences>p|a|p|a|a|p|da|p|da|da</sequences></card>
    <card><id>11</id><name>Grey Wolf</name><image>e_forest_8</image><life>16</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>minion</innate><world>forest</world><sequences>a|a|a|a|p|a|a|a|a|p</sequences></card>
    <card><id>12</id><name>Lycanthrope</name><image>e_forest_9</image><life>72</life><attack>12</attack><armor></armor><heal></heal><call>11</call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>wolf_leather</innate><world>forest</world><sequences>e|a|p|e|a|p|e|da|p|da</sequences></card>
    <card><id>13</id><name>Forest Wyvern</name><image>e_forest_10</image><life>88</life><attack>9</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>2</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>emerald_skin</innate><world>forest</world><sequences>ws|a|a|a|ws|a|a|a|ws|p</sequences></card>
    <card><id>14</id><name>Giant Wasp</name><image>e_forest_11</image><life>40</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>ws|a|wa|a|ws|a|wa|a|ws|a</sequences></card>
    <card><id>15</id><name>Giant Wasp</name><image>e_forest_11</image><life>40</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>a|p|a|p|a|p|a|p|a|p</sequences></card>
    <card><id>16</id><name>Giant Wasp</name><image>e_forest_11</image><life>40</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>wa|a|ws|a|wa|a|ws|a|wa|a</sequences></card>
    <card><id>17</id><name>Gorilla King</name><image>e_forest_12</image><life>123</life><attack>1</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>banana_power</innate><world>forest</world><sequences>p|a|a|a|a|p|a|a|a|a</sequences></card>
    <card><id>18</id><name>Night Faun</name><image>e_forest_7</image><life>36</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>forest</world><sequences>a|a|p|a|a|p|da|da|p|p</sequences></card>
    <card><id>19</id><name>Evil Forest Guardian</name><image>e_forest_13</image><life>99</life><attack></attack><armor></armor><heal>10</heal><call></call><weakness>0</weakness><frail>0</frail><curse>2</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>poisonous_berries</innate><world>forest</world><sequences>p|cc|ha|p|p|cc|ha|p|p|ha</sequences></card>

    <!--WATER-->
    <card><id>20</id><name>Mutant Starfish</name><image>e_water_1</image><life>23</life><attack>4</attack><armor>8</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>seaworld</world><sequences>a|s|a|s|p|a|s|a|s|p</sequences></card>
    <card><id>21</id><name>Inhabitant of the Abyss</name><image>e_water_2</image><life>62</life><attack>4</attack><armor>4</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>1</wound><innate></innate><world>seaworld</world><sequences>wd|a|s|a|s|a|s|wd|da|da</sequences></card>
    <card><id>22</id><name>Giant Squid</name><image>e_water_3</image><life>29</life><attack>6</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>ink_hit</innate><world>seaworld</world><sequences>a|ws|a|a|p|wa|a|p|a|p</sequences></card>
    <card><id>23</id><name>Giant Squid</name><image>e_water_3</image><life>29</life><attack>6</attack><armor></armor><heal></heal><call></call><weakness>1</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>ink_hit</innate><world>seaworld</world><sequences>wa|a|a|p|ws|a|a|p|a|p</sequences></card>
    <card><id>24</id><name>Electric Moray</name><image>e_water_5</image><life>21</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>2</block><silence>0</silence><wound>0</wound><innate>electroshock</innate><world>seaworld</world><sequences>p|a|da|p|a|a|bk|a|da|aa</sequences></card>
    <card><id>25</id><name>Electric Moray</name><image>e_water_5</image><life>21</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>2</block><silence>0</silence><wound>0</wound><innate>electroshock</innate><world>seaworld</world><sequences>a|a|p|a|p|p|da|p|da|p</sequences></card>
    <card><id>26</id><name>Electric Moray</name><image>e_water_5</image><life>21</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>2</block><silence>0</silence><wound>0</wound><innate>electroshock</innate><world>seaworld</world><sequences>a|p|p|a|da|p|p|a|p|da</sequences></card>
    <card><id>27</id><name>Vampire Fish</name><image>e_water_4</image><life>66</life><attack>6</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>3</wound><innate>drain_blood</innate><world>seaworld</world><sequences>wd|a|p|a|p|a|p|wd|da|da</sequences></card>
    <card><id>28</id><name>Giant Shark</name><image>e_water_6</image><life>34</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>smell_blood</innate><world>seaworld</world><sequences>a|a|a|a|p|a|a|a|a|p</sequences></card>
    <card><id>29</id><name>Gyozu the Fisheater</name><image>e_water_7</image><life>99</life><attack>18</attack><armor></armor><heal>9</heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>fish_eater</innate><world>seaworld</world><sequences>a|a|p|p|a|a|p|p|a|a</sequences></card>
    <card><id>30</id><name>Electric Jellyfish</name><image>e_water_8</image><life>70</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>electric_field</innate><world>seaworld</world><sequences>p|a|a|da|p|p|a|a|p|p</sequences></card>
    <card><id>31</id><name>Electric Jellyfish</name><image>e_water_8</image><life>70</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>electric_field</innate><world>seaworld</world><sequences>p|a|p|p|a|a|p|p|a|da</sequences></card>
    <card><id>32</id><name>White Sea Snake (1st Form)</name><image>e_water_9</image><life>55</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>evolve_death</innate><world>seaworld</world><sequences>a|p|a|a|p|a|a|p|da|da</sequences></card>
    <card><id>33</id><name>White Sea Snake (Ultimate Form)</name><image>e_water_10</image><life>70</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>1</silence><wound>0</wound><innate>shock_wave_hit</innate><world>seaworld</world><sequences>da|p|a|a|p|p|a|p|p|da</sequences></card>
    <card><id>34</id><name>Black Sea Snake (1st Form)</name><image>e_water_11</image><life>55</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>1</block><silence>0</silence><wound>0</wound><innate>evolve_death</innate><world>seaworld</world><sequences>a|p|a|a|p|a|a|p|da|da</sequences></card>
    <card><id>35</id><name>Black Sea Snake (Ultimate Form)</name><image>e_water_12</image><life>90</life><attack>9</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>seaworld</world><sequences>a|p|da|a|p|da|a|p|da|da</sequences></card>
    <card><id>36</id><name>Angler Leviathan</name><image>e_water_13</image><life>100</life><attack>10</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>2</silence><wound>0</wound><innate>deadly_bait</innate><world>seaworld</world><sequences>a|p|p|da|sl|p|p|a|a|p</sequences></card>

    <!--DESERT-->
    <card><id>37</id><name>Mulog</name><image>e_desert_1</image><life>29</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>rage</innate><world>desert</world><sequences>p|a|p|a|p|da|p|da|p|da</sequences></card>
    <card><id>38</id><name>Lesser Stone Essence</name><image>e_desert_2</image><life>45</life><attack>5</attack><armor>5</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>desert</world><sequences>a|s|s|a|a|s|s|a|a|s</sequences></card>
    <card><id>39</id><name>Elder Snake</name><image>e_desert_3</image><life>45</life><attack>4</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>snake_poison</innate><world>desert</world><sequences>a|a|p|a|a|a|p|a|a|p</sequences></card>
    <card><id>40</id><name>Stone Hound</name><image>e_desert_10</image><life>18</life><attack>4</attack><armor>20</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>armored</innate><world>desert</world><sequences>s|a|s|p|a|p|p|a|s|p</sequences></card>
    <card><id>41</id><name>Stone Hound</name><image>e_desert_10</image><life>18</life><attack>4</attack><armor>20</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>armored</innate><world>desert</world><sequences>a|s|p|s|a|p|a|p|p|s</sequences></card>
    <card><id>42</id><name>Sand Monster</name><image>e_desert_13</image><life>8</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>dissolve</innate><world>desert</world><sequences>a|a|a|a|a|a|a|a|a|a</sequences></card>
    <card><id>43</id><name>Sand Demon</name><image>e_desert_5</image><life>49</life><attack>5</attack><armor></armor><heal></heal><call>42</call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>sand_creation</innate><world>desert</world><sequences>a|p|a|p|a|p|a|p|a|p</sequences></card>
    <card><id>44</id><name>Rock Giant</name><image>e_desert_6</image><life>210</life><attack>21</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>1</block><silence>0</silence><wound>0</wound><innate>fissure</innate><world>desert</world><sequences>p|p|p|p|p|p|p|p|p|p</sequences></card>
    <card><id>45</id><name>Cobra</name><image>e_desert_7</image><life>30</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>desert</world><sequences>a|p|a|a|p|p|da|da|p|da</sequences></card>
    <card><id>46</id><name>Desert Cultist</name><image>e_desert_8</image><life>33</life><attack>3</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>desert</world><sequences>p|a|a|p|p|a|a|p|p|a</sequences></card>
    <card><id>47</id><name>Desert Wizard</name><image>e_desert_9</image><life>200</life><attack>7</attack><armor></armor><heal></heal><call>46</call><weakness>1</weakness><frail>1</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>desert_thunder</innate><world>desert</world><sequences>ws|wa|a|p|e|e|wa|ws|a|p</sequences></card>
    <card><id>48</id><name>Hibaku</name><image>e_desert_11</image><life>168</life><attack>8</attack><armor>8</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>radiant_shield</innate><world>desert</world><sequences>s|da|s|da|s|s|da|a|da|s</sequences></card>
    <card><id>49</id><name>Exploding Stone</name><image>e_desert_12</image><life>12</life><attack>6</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>explosive</innate><world>desert</world><sequences>a|p|a|p|a|p|a|p|a|p</sequences></card>
    <card><id>50</id><name>Elder Stone Essence</name><image>e_desert_4</image><life>100</life><attack>10</attack><armor></armor><heal></heal><call>49</call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>tough_skin</innate><world>desert</world><sequences>p|a|da|e|p|a|e|da|da|e</sequences></card>
    <!--<card><id>50</id><name>God of Sand</name><image>e_d_10</image><life>200</life><attack>10</attack><armor>20</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>3</curse><blind>0</blind><block>1</block><silence>1</silence><wound>0</wound><innate>sand_bless</innate><world>desert</world><sequences>bk|a|da|da|sl|bk|a|da|da|sl</sequences></card>-->

    <!--LOSTWORLD-->
    <card><id>51</id><name>Giant Bat</name><image>e_lostworld_1</image><life>31</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>sonic_alarm</innate><world>lostworld</world><sequences>a|a|p|p|a|p|p|da|p|p</sequences></card>
    <card><id>52</id><name>Giant Bat</name><image>e_lostworld_1</image><life>31</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>sonic_alarm</innate><world>lostworld</world><sequences>a|p|a|a|p|p|da|a|p|a</sequences></card>
    <card><id>53</id><name>Giant Bat</name><image>e_lostworld_1</image><life>31</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>sonic_alarm</innate><world>lostworld</world><sequences>p|a|a|a|a|da|p|p|a|a</sequences></card>
    <card><id>54</id><name>Pterodactyl</name><image>e_lostworld_2</image><life>44</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>flying</innate><world>lostworld</world><sequences>a|p|da|a|p|da|p|p|da|da</sequences></card>
    <card><id>55</id><name>Pterodactyl</name><image>e_lostworld_2</image><life>44</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>flying</innate><world>lostworld</world><sequences>p|da|a|p|da|p|p|da|da|a</sequences></card>
    <card><id>56</id><name>Scysr</name><image>e_lostworld_3</image><life>50</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>piercing</innate><world>lostworld</world><sequences>a|p|a|p|a|p|a|p|a|p</sequences></card>
    <card><id>57</id><name>Scysr</name><image>e_lostworld_3</image><life>50</life><attack>5</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>piercing</innate><world>lostworld</world><sequences>p|a|p|a|p|a|p|a|p|a</sequences></card>
    <card><id>58</id><name>Lizard Saurus</name><image>e_lostworld_4</image><life>50</life><attack>14</attack><armor>8</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>lostworld</world><sequences>s|a|p|s|s|da|p|a|s|a</sequences></card>
    <card><id>59</id><name>Lizard Saurus</name><image>e_lostworld_4</image><life>50</life><attack>14</attack><armor>8</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>lostworld</world><sequences>a|s|p|s|da|s|a|p|a|s</sequences></card>
    <card><id>60</id><name>Raptor</name><image>e_lostworld_5</image><life>30</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>1</wound><innate>bite</innate><world>lostworld</world><sequences>a|p|a|a|p|a|p|a|a|p</sequences></card>
    <card><id>61</id><name>Raptor</name><image>e_lostworld_5</image><life>30</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>1</wound><innate>bite</innate><world>lostworld</world><sequences>p|a|p|a|a|p|a|p|a|a</sequences></card>
    <card><id>62</id><name>Raptor</name><image>e_lostworld_5</image><life>30</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>1</wound><innate>bite</innate><world>lostworld</world><sequences>a|p|a|a|p|a|p|a|a|p</sequences></card>
    <card><id>63</id><name>Scavenger</name><image>e_lostworld_10</image><life>77</life><attack>7</attack><armor>7</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>saprofagus</innate><world>lostworld</world><sequences>p|a|sa|da|p|da|a|sa|a|sa</sequences></card>
    <card><id>64</id><name>Scavenger</name><image>e_lostworld_10</image><life>77</life><attack>7</attack><armor>7</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>saprofagus</innate><world>lostworld</world><sequences>sa|p|a|sa|da|p|da|a|sa|a</sequences></card>
    <card><id>65</id><name>Scavenger</name><image>e_lostworld_10</image><life>77</life><attack>7</attack><armor>7</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>saprofagus</innate><world>lostworld</world><sequences>a|sa|p|a|sa|da|p|da|a|sa</sequences></card>
    <card><id>66</id><name>Mutant Insect</name><image>e_lostworld_8</image><life>204</life><attack>4</attack><armor>8</armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>wild_growth</innate><world>lostworld</world><sequences>s|a|da|a|s|a|da|a|s|da</sequences></card>
    <card><id>67</id><name>Tyrannosaurus Elite</name><image>e_lostworld_6</image><life>202</life><attack>11</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>2</wound><innate></innate><world>lostworld</world><sequences>a|wd|a|da|p|da|p|p|a|da</sequences></card>
    <card><id>68</id><name>Terror Disciple</name><image>e_lostworld_9</image><life>108</life><attack>8</attack><armor></armor><heal></heal><call>69</call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>call_terror</innate><world>lostworld</world><sequences>a|p|a|a|p|da|p|p|da|da</sequences></card>
    <card><id>69</id><name>Terror of the Depths</name><image>e_lostworld_7</image><life>280</life><attack>28</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate></innate><world>landofdragons</world><sequences>p|p|a|a|a|p|da|p|a|da</sequences></card>
    <card><id>70</id><name>Saurus King (1st Form)</name><image>e_lostworld_11</image><life>105</life><attack>12</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>3</wound><innate>evolve_death</innate><world>lostworld</world><sequences>wd|p|a|a|p|a|a|p|da|da</sequences></card>
    <card><id>71</id><name>Saurus King (Ultimate Form)</name><image>e_lostworld_12</image><life>205</life><attack>20</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>3</wound><innate></innate><world>lostworld</world><sequences>p|p|da|da|p|da|a|wd|a|da</sequences></card>

    <!--NEW ELITE LOSTWORLD-->
    <card><id>72</id><name>Saber Tooth</name><image>e_lostworld_13</image><life>42</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>bite</innate><world>lostworld</world><sequences>p|a|p|da|a|p|a|a|a|a</sequences></card>
    <card><id>73</id><name>Saber Tooth</name><image>e_lostworld_13</image><life>42</life><attack>7</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>bite</innate><world>lostworld</world><sequences>p|a|da|a|p|a|a|p|a|p</sequences></card>
    <card><id>74</id><name>Turan the Ancient Tiger</name><image>e_lostworld_14</image><life>142</life><attack>15</attack><armor></armor><heal>7</heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>rage</innate><world>lostworld</world><sequences>p|p|a|ha|da|a|a|p|p|da</sequences></card>

    <!--UNDEAD-->
    <card><id>75</id><name>Cemetery Ghost</name><image>e_reignofdead_1</image><life>48</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>fear</innate><world>reignofdead</world><sequences>p|a|a|p|a|a|p|da|p|da</sequences></card>
    <card><id>76</id><name>Cemetery Ghost</name><image>e_reignofdead_1</image><life>48</life><attack>8</attack><armor></armor><heal></heal><call></call><weakness>0</weakness><frail>0</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>fear</innate><world>reignofdead</world><sequences>da|p|a|a|p|a|a|p|a|a</sequences></card>
    <card><id>77</id><name>Gargoyle</name><image>e_reignofdead_17</image><life>39</life><attack>9</attack><armor>9</armor><heal></heal><call></call><weakness>2</weakness><frail>2</frail><curse>0</curse><blind>0</blind><block>0</block><silence>0</silence><wound>0</wound><innate>flying</innate><world>reignofdead</world><sequences>wa|a|p|s|s|a|p|da|da|ws</sequences></card>